name = "COOPS 5"
author = "Pablo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b68c651f368fe93e732ce88cdcba5cd6b5e8fe6bff85d947ec366098abb19d2c"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
