name = "COOPS 5"
author = "Pablo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd83b6f4ac03b7a43308606d4214c2031f8a08e5b822aab2270e0e57ecd64106"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
