name = "COOPS 5"
author = "Pablo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fbe08283a0279c93bf69c1d77661562f66e51585fb7862b7987a156f71f7e21d"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
