name = "COOPS 5"
author = "Pablo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d10ca7471733d53466ee93ce2838ba392debf8551197524c44dcd83f13460e19"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
