name = "COOPS 5"
author = "Pablo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0a18ac1c1f88352fdaf57fac8afcc7effa2b67b80b54c2c4d0357fe4bbcebc0"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
