name = "COOPS 5"
author = "Pablo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a0824ed79831a971b693ef7bb3f24af54d19f043a6bbdeb5a7828ecc1912bd5"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
